// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm36Xnb5f-mxZPOi80t_qfSrDoLEY2NDc',
    appId: '1:977148141535:web:115016cfce50166726ee6a',
    messagingSenderId: '977148141535',
    projectId: 'jobportalapp-ec316',
    authDomain: 'jobportalapp-ec316.firebaseapp.com',
    storageBucket: 'jobportalapp-ec316.firebasestorage.app',
    measurementId: 'G-FWJFNM3GQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhZNEJSbbzzprxSpFLwW6khawSByx84B0',
    appId: '1:977148141535:android:c8b12a77e414cf8226ee6a',
    messagingSenderId: '977148141535',
    projectId: 'jobportalapp-ec316',
    storageBucket: 'jobportalapp-ec316.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR7s0kGQZKFwkhEAv7AYRFHocDXrf1sH0',
    appId: '1:977148141535:ios:272811b6729608ba26ee6a',
    messagingSenderId: '977148141535',
    projectId: 'jobportalapp-ec316',
    storageBucket: 'jobportalapp-ec316.firebasestorage.app',
    iosBundleId: 'com.example.jobPortalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR7s0kGQZKFwkhEAv7AYRFHocDXrf1sH0',
    appId: '1:977148141535:ios:272811b6729608ba26ee6a',
    messagingSenderId: '977148141535',
    projectId: 'jobportalapp-ec316',
    storageBucket: 'jobportalapp-ec316.firebasestorage.app',
    iosBundleId: 'com.example.jobPortalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm36Xnb5f-mxZPOi80t_qfSrDoLEY2NDc',
    appId: '1:977148141535:web:9b53ed294920618f26ee6a',
    messagingSenderId: '977148141535',
    projectId: 'jobportalapp-ec316',
    authDomain: 'jobportalapp-ec316.firebaseapp.com',
    storageBucket: 'jobportalapp-ec316.firebasestorage.app',
    measurementId: 'G-1SJVXBWX95',
  );
}
